name: CI / Bump version
on:
    push:
        branches:
            - main
jobs:
    bump:
        name: "Bump Version"
        runs-on: ubuntu-latest
        steps:
            - name: "Update package version on release with semver"
              uses: "pkgacek/update-package-version-on-release@v1.1"
